name: new_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  get: ^4.6.6
  firebase_auth: ^5.1.1
  http_requests: ^3.2.0
  logger: ^2.3.0
  image_picker_android: ^0.8.12+3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.2.0

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
