// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxa-txEb0CZ9llEXSK-tXmq13uiCoyDak',
    appId: '1:526880989601:web:7826a48748195ff9262be0',
    messagingSenderId: '526880989601',
    projectId: 'new-app-79471',
    authDomain: 'new-app-79471.firebaseapp.com',
    storageBucket: 'new-app-79471.appspot.com',
    measurementId: 'G-V934CPDVR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5utt2LkrSE4pVURzRiYtX3qplrlV19hU',
    appId: '1:526880989601:android:ee9ee3b33590c49b262be0',
    messagingSenderId: '526880989601',
    projectId: 'new-app-79471',
    storageBucket: 'new-app-79471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgLsxVbZxKtlfo5WF9pjunMSh7jrPxObw',
    appId: '1:526880989601:ios:202e855c452137a0262be0',
    messagingSenderId: '526880989601',
    projectId: 'new-app-79471',
    storageBucket: 'new-app-79471.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgLsxVbZxKtlfo5WF9pjunMSh7jrPxObw',
    appId: '1:526880989601:ios:202e855c452137a0262be0',
    messagingSenderId: '526880989601',
    projectId: 'new-app-79471',
    storageBucket: 'new-app-79471.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxa-txEb0CZ9llEXSK-tXmq13uiCoyDak',
    appId: '1:526880989601:web:fd9669f91cca656d262be0',
    messagingSenderId: '526880989601',
    projectId: 'new-app-79471',
    authDomain: 'new-app-79471.firebaseapp.com',
    storageBucket: 'new-app-79471.appspot.com',
    measurementId: 'G-17W5DB2BKX',
  );
}
